config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get :home, to: "static_pages#home"
    get :help, to: "static_pages#help"
    get :login, to: "sessions#new"
    post :login, to: "sessions#create"
    delete :logout, to: "sessions#destroy"
    get "password_resets/new"
    get "password_resets/edit"

    resources :users
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t("pages.footer.the") %>
    <%= link_to t("pages.home.ruby_on_rails"), "http://www.railstutorial.org" %>
    <%= t("pages.footer.by") %>
    <%= link_to "Michael Hartl", "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("pages.footer.about"), "#" %></li>
      <li><%= link_to t("pages.footer.contact"), "#" %></li>
      <li>
        <%= link_to t("pages.footer.news"), "http://news.railstutorial.org/" %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: @user %>
  <%= f.label :name, t("pages.signup.name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t("pages.signup.email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t("pages.signup.password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("pages.signup.confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("pages.nav.sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("pages.nav.home"), home_path %></li>
        <li><%= link_to t("pages.nav.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("pages.nav.user"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t("pages.nav.account") %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("pages.nav.profile"), current_user %></li>
              <li><%= link_to t("pages.nav.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("pages.nav.log_out"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("pages.nav.log_in"), login_path %></li>
        <% end %>
        <li><%= link_to t("pages.nav.eng"), locale: :en %></li>
        <li><%= link_to t("pages.nav.vie"), locale: :vi %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "custom", media: "all",
      "data-turbolinks-track" => true %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>